### PR TITLE
Email-NodeMailer

### PR DESCRIPTION
**Pull request by NazimFilzer**
#42  Please Do the Nessacery Review

### CODE REVIEW

**Comment by Bachittarjeet** [comment]
Accepted!!

**Comment by NazimFilzer** [comment]
> Accepted!!

Thanks!!.. Will this be Counted in Hactoberfest Fest? Anything from my side i should do?

**Comment by NazimFilzer** [comment]
Also @Bachittarjeet Can i make more PR over here?

**Comment by Bachittarjeet** [comment]
> > Accepted!!
> 
> 
> 
> Thanks!!.. Will this be Counted in Hactoberfest Fest? Anything from my side i should do?

Yes! Assuming you've already registered on Hacktoberfest website

**Comment by Bachittarjeet** [comment]
> Also @Bachittarjeet Can i make more PR over here?

Sure! But for hacktoberfest try to contribute to other opensource repositories too 😊

**Comment by NazimFilzer** [comment]
> > Also @Bachittarjeet Can i make more PR over here?
> 
> Sure! But for hacktoberfest try to contribute to other opensource repositories too 😊

 I am a Nodejs Dev and i find it too hard to find simple repos 🥺

**Pull request merged**
